### ISSUE TITLE
Sending VeChain tokens from Ledger Live require contract data to be enabled on the VeChain app

### ISSUE THREAD

**Issue by tdejoigny-ledger** [LedgerHQ/app-vechain#33]
**Description**

Sending VeChain tokens from Ledger Live require contract data to be enabled on the VeChain app

**Steps to reproduce**

Have some VeChain tokens in a Vechain account in Ledger Live

Try to send a transaction without Contract Data enabled

**Expected behavior**

User should be able to clear-sign and not have to enable contract data in the app settings.

**Comment by LucaGenoni** [comment]
Hi @tdejoigny-ledger 

Thank you for raising this issue.
From what I saw, the current behaviour is:
- If Contract Data is enabled, alert the user if there is data in any clause of the tx; otherwise, reject any tx with data in the clauses.

Can you clarify what is the expected behaviour between:
1. The user should always be able to clear-sign, even if there is data in at least one clause of the TX. 
2. The user should always be able to clear-sign, and if contract data is disabled, then from the ledger live, we should not add data to the clauses of the TX.
 
If the expected behaviour is 1, then I can easily change the setting in app-vechain to:
- If Contract Data is enabled, alert the user if there is any data in a transaction; otherwise, do not alert the user and clear-sign.

If the expected behaviour is 2, then we should change the ledger live vechain implementation to:
- Retrieve the setting before sending any TX and avoid adding data to a TX if contract data is disabled.
